WebApp.Modal/Controllers/ClienteViewModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Modal.Models;
using WebApp.Modal.ViewModels;

namespace WebApp.Modal.Controllers
{
    public class ClienteViewModelsController : Controller
    {
        private readonly testeContext _context;
        private readonly IMapper _mapper;

        public ClienteViewModelsController(testeContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper; 
        }

        // GET: ClienteViewModels
        public async Task<IActionResult> Index()
        {

            return View(_mapper.Map<IEnumerable<ClienteViewModel>>(await _context.Clientes.ToListAsync()));
        }

        // GET: ClienteViewModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ClienteViewModel == null)
            {
                return NotFound();
            }

            var clienteViewModel = await _context.ClienteViewModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clienteViewModel == null)
            {
                return NotFound();
            }

            return View(clienteViewModel);
        }

        // GET: ClienteViewModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ClienteViewModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome")] ClienteViewModel clienteViewModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clienteViewModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(clienteViewModel);
        }

        // GET: ClienteViewModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ClienteViewModel == null)
            {
                return NotFound();
            }

            var clienteViewModel = _mapper.Map<ClienteViewModel>(await _context.Clientes.FindAsync(id));

            clienteViewModel.ServicosClientes = _mapper.Map<IEnumerable<ServicosClientesViewModel>>(await _context.ServicosClientes.Where(s => s.ClienteId == id).Include(s => s.Servico).ToListAsync());

            if (clienteViewModel == null)
                return NotFound();

            return View(clienteViewModel);
        }

        // POST: ClienteViewModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome")] ClienteViewModel clienteViewModel)
        {
            if (id != clienteViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(_mapper.Map<Cliente>(clienteViewModel));
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteViewModelExists(clienteViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(clienteViewModel);
        }

        // GET: ClienteViewModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ClienteViewModel == null)
            {
                return NotFound();
            }

            var clienteViewModel = await _context.ClienteViewModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clienteViewModel == null)
            {
                return NotFound();
            }

            return View(clienteViewModel);
        }

        // POST: ClienteViewModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ClienteViewModel == null)
            {
                return Problem("Entity set 'testeContext.ClienteViewModel'  is null.");
            }
            var clienteViewModel = await _context.ClienteViewModel.FindAsync(id);
            if (clienteViewModel != null)
            {
                _context.ClienteViewModel.Remove(clienteViewModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteViewModelExists(int id)
        {
          return (_context.ClienteViewModel?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApp.Modal/Controllers/ServicosClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Modal.Models;
using WebApp.Modal.ViewModels;

namespace WebApp.Modal.Controllers
{
    public class ServicosClientesController : Controller
    {
        private readonly testeContext _context;
        private readonly IMapper _mapper;

        public ServicosClientesController(testeContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        // GET: ServicosClientes
        public async Task<IActionResult> Index()
        {
            var testeContext = _mapper.Map<ServicosClientesViewModel>(await _context.ServicosClientes.Include(s => s.Cliente).Include(s => s.Servico).ToListAsync());
            
            return View(testeContext);
        }

        // GET: ServicosClientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ServicosClientesViewModel == null)
            {
                return NotFound();
            }

            var servicosClientesViewModel = await _context.ServicosClientesViewModel
                .Include(s => s.Cliente)
                .Include(s => s.Servico)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (servicosClientesViewModel == null)
            {
                return NotFound();
            }

            return View(servicosClientesViewModel);
        }

        // GET: ServicosClientes/Create
        public IActionResult Create()
        {
            ViewData["ClienteId"] = new SelectList(_context.ClienteViewModel, "Id", "Nome");
            ViewData["ServicoId"] = new SelectList(_context.Set<ServicoViewModel>(), "Id", "Descricao");
            return View();
        }

        // POST: ServicosClientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ClienteId,ServicoId")] ServicosClientesViewModel servicosClientesViewModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(servicosClientesViewModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.ClienteViewModel, "Id", "Id", servicosClientesViewModel.ClienteId);
            ViewData["ServicoId"] = new SelectList(_context.Set<ServicoViewModel>(), "Id", "Id", servicosClientesViewModel.ServicoId);
            return View(servicosClientesViewModel);
        }

        // GET: ServicosClientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ServicosClientesViewModel == null)
            {
                return NotFound();
            }

            var servicosClientesViewModel = _mapper.Map<ServicosClientesViewModel>(await _context.ServicosClientes.Include(c => c.Cliente).FirstAsync(e => e.Id == id));

            if (servicosClientesViewModel == null)
                return NotFound();

            //ViewData["ClienteId"] = new SelectList(_context.Set<ClienteViewModel>(), "Id", "Nome", servicosClientesViewModel.ClienteId);
            ViewData["ServicoId"] = new SelectList(_mapper.Map<IEnumerable<ServicoViewModel>>(_context.Set<Servico>()), "Id", "Descricao", servicosClientesViewModel.ServicoId);
            return View(servicosClientesViewModel);
        }

        // POST: ServicosClientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ClienteId,ServicoId")] ServicosClientesViewModel servicosClientesViewModel)
        {
            if (id != servicosClientesViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(_mapper.Map<ServicosCliente>(servicosClientesViewModel));
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServicosClientesViewModelExists(servicosClientesViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.ClienteViewModel, "Id", "Nome", servicosClientesViewModel.ClienteId);
            ViewData["ServicoId"] = new SelectList(_context.Set<ServicoViewModel>(), "Id", "Descricao", servicosClientesViewModel.ServicoId);
            return View(servicosClientesViewModel);
        }

        // GET: ServicosClientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ServicosClientesViewModel == null)
            {
                return NotFound();
            }

            var servicosClientesViewModel = await _context.ServicosClientesViewModel
                .Include(s => s.Cliente)
                .Include(s => s.Servico)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (servicosClientesViewModel == null)
            {
                return NotFound();
            }

            return View(servicosClientesViewModel);
        }

        // POST: ServicosClientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ServicosClientesViewModel == null)
            {
                return Problem("Entity set 'testeContext.ServicosClientesViewModel'  is null.");
            }
            var servicosClientesViewModel = await _context.ServicosClientesViewModel.FindAsync(id);
            if (servicosClientesViewModel != null)
            {
                _context.ServicosClientesViewModel.Remove(servicosClientesViewModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServicosClientesViewModelExists(int id)
        {
          return (_context.ServicosClientesViewModel?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApp.Modal/Controllers/ServicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Modal.Models;
using WebApp.Modal.ViewModels;

namespace WebApp.Modal.Controllers
{
    public class ServicosController : Controller
    {
        private readonly testeContext _context;

        public ServicosController(testeContext context)
        {
            _context = context;
        }

        // GET: Servicos
        public async Task<IActionResult> Index()
        {
              return _context.ServicoViewModel != null ? 
                          View(await _context.ServicoViewModel.ToListAsync()) :
                          Problem("Entity set 'testeContext.ServicoViewModel'  is null.");
        }

        // GET: Servicos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ServicoViewModel == null)
            {
                return NotFound();
            }

            var servicoViewModel = await _context.ServicoViewModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (servicoViewModel == null)
            {
                return NotFound();
            }

            return View(servicoViewModel);
        }

        // GET: Servicos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Servicos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Descricao")] ServicoViewModel servicoViewModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(servicoViewModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(servicoViewModel);
        }

        // GET: Servicos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ServicoViewModel == null)
            {
                return NotFound();
            }

            var servicoViewModel = await _context.ServicoViewModel.FindAsync(id);
            if (servicoViewModel == null)
            {
                return NotFound();
            }
            return View(servicoViewModel);
        }

        // POST: Servicos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Descricao")] ServicoViewModel servicoViewModel)
        {
            if (id != servicoViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(servicoViewModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServicoViewModelExists(servicoViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(servicoViewModel);
        }

        // GET: Servicos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ServicoViewModel == null)
            {
                return NotFound();
            }

            var servicoViewModel = await _context.ServicoViewModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (servicoViewModel == null)
            {
                return NotFound();
            }

            return View(servicoViewModel);
        }

        // POST: Servicos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ServicoViewModel == null)
            {
                return Problem("Entity set 'testeContext.ServicoViewModel'  is null.");
            }
            var servicoViewModel = await _context.ServicoViewModel.FindAsync(id);
            if (servicoViewModel != null)
            {
                _context.ServicoViewModel.Remove(servicoViewModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServicoViewModelExists(int id)
        {
          return (_context.ServicoViewModel?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApp.Modal/Views/ClienteViewModels/Create.cshtml
@model WebApp.Modal.ViewModels.ClienteViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ClienteViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp.Modal/Views/ClienteViewModels/Delete.cshtml
@model WebApp.Modal.ViewModels.ClienteViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ClienteViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApp.Modal/Views/ClienteViewModels/Details.cshtml
@model WebApp.Modal.ViewModels.ClienteViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ClienteViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApp.Modal/Views/ClienteViewModels/Edit.cshtml
@model WebApp.Modal.ViewModels.ClienteViewModel


<h1>Edit</h1>

<h4>ClienteViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@await Html.PartialAsync("_Servicos")

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp.Modal/Views/ClienteViewModels/Index.cshtml
@model IEnumerable<WebApp.Modal.ViewModels.ClienteViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

WebApp.Modal/Views/ClienteViewModels/_Servicos.cshtml
@model WebApp.Modal.ViewModels.ClienteViewModel

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
               Cliente
            </th>
            <th>
              Serviços
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.ServicosClientes) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Cliente.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Servico.Descricao)
            </td>
            <td>
                <a asp-controller="ServicosClientes" asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>